/**
 * Full knowledge base ingestion — ~200 remedies, all Organon aphorisms, 300+ rubrics
 * Run: node scripts/ingest-full.mjs
 */
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const env = Object.fromEntries(
  readFileSync(join(__dirname, "../.env.local"), "utf8")
    .split("\n").filter(l => l.includes("="))
    .map(l => { const i = l.indexOf("="); return [l.slice(0,i).trim(), l.slice(i+1).trim()]; })
);

const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

async function upsert(docs) {
  for (const doc of docs) {
    process.stdout.write(`  ${doc.title}...`);
    const { error } = await supabase.from("knowledge_documents").upsert(
      { source: doc.source, category: doc.category, title: doc.title, content: doc.content, metadata: doc.metadata || {} },
      { onConflict: "title" }
    );
    console.log(error ? ` ✗ ${error.message}` : " ✓");
  }
}

// ─── REMEDIES ────────────────────────────────────────────────────────────────
const remedies = [
  { name:"Apis Mellifica", abbr:"Apis", cat:"animal", const:"Busy, restless, jealous, stinging pains",
    keys:["Stinging, burning pains","Oedema — pitting, watery swellings","Worse heat, better cold","Jealousy, suspicion","No thirst"],
    mind:["Busy, industrious","Jealousy","Sudden changes of mood","Apathy alternating with activity"],
    worse:["Heat","Touch","Pressure","Right side"], better:["Cold","Open air","Uncovering"],
    comp:["Natrum Mur","Pulsatilla"], anti:["Carbolic Acid","Lachesis"] },
  { name:"Argentum Nitricum", abbr:"Arg-n.", cat:"mineral", const:"Anxious, hurried, impulsive, craves sugar",
    keys:["Anticipatory anxiety","Craves sweets — aggravates","Diarrhoea from excitement","Splinter-like pains","Worse warmth"],
    mind:["Hurried, impulsive","Fear of heights, crowds","Anticipation anxiety","Time passes slowly"],
    worse:["Warmth","Sugar","Emotion","Night"], better:["Cold","Open air","Pressure"],
    comp:["Natrum Mur"], anti:["Natrum Mur","Arsenicum"] },
  { name:"Aurum Metallicum", abbr:"Aur.", cat:"mineral", const:"Suicidal depression, sense of duty, failure",
    keys:["Suicidal depression","Bone pains at night","Hypertension","Sense of guilt, self-condemnation","Religious melancholy"],
    mind:["Deep depression","Suicidal thoughts","Sense of failure","Desire to die","Workaholic — then collapse"],
    worse:["Night","Cold","Mental exertion"], better:["Warmth","Music","Walking in fresh air"],
    comp:["Silica","Iodum"], anti:["Belladonna","Mercurius"] },
  { name:"Baryta Carbonica", abbr:"Bar-c.", cat:"mineral", const:"Mentally and physically delayed child or old person",
    keys:["Childlike timidity in adults","Bashful, lacks confidence","Tonsil hypertrophy","Dwarfishness — mental and physical","Senility"],
    mind:["Bashful, timid","Childlike","Irresolute","Fear of strangers","Memory weakness"],
    worse:["Cold","Damp","Thinking of symptoms"], better:["Warmth"],
    comp:["Silica","Dulcamara"], anti:["Camphor"] },
  { name:"Borax", abbr:"Bor.", cat:"mineral", const:"Nervous, sensitive to downward motion",
    keys:["Fear of downward motion","Aphthous ulcers","Anxiety from downward motion","Breastfed baby lets go crying","Worse noise"],
    mind:["Nervous, anxious","Fear of downward motion","Easily startled","Anxiety from slight sounds"],
    worse:["Downward motion","Noise","Warm weather"], better:["Cold","Evening","Pressure"],
    comp:["Calcarea","Silica"], anti:["Coffea"] },
  { name:"Causticum", abbr:"Caust.", cat:"mineral", const:"Sympathetic, idealistic, paralytic weakness",
    keys:["Paralysis — facial, vocal, bladder","Warts on nose and hands","Sympathetic to suffering of others","Rawness, soreness","Worse dry cold wind"],
    mind:["Sympathetic, compassionate","Intensely idealistic","Angry at injustice","Grief from losing friends"],
    worse:["Dry cold wind","Motion","Clear fine weather"], better:["Damp weather","Warmth"],
    comp:["Colocynthis","Petroleum"], anti:["Phosphorus","Coffea"] },
  { name:"Chamomilla", abbr:"Cham.", cat:"plant", const:"Irritable, hypersensitive to pain, demands and rejects",
    keys:["Extreme irritability — cannot bear pain","Demands things then throws them away","One cheek red, one pale","Better being carried","Teething child"],
    mind:["Irritable beyond endurance","Capricious","Children want to be carried","Angry","Oversensitive to pain"],
    worse:["Heat","Anger","Night","Wind"], better:["Being carried","Cold applications","Fasting"],
    comp:["Belladonna","Magnesia Carb"], anti:["Pulsatilla","Nux Vomica"] },
  { name:"China Officinalis", abbr:"Chin.", cat:"plant", const:"Debility from fluid loss, periodic complaints",
    keys:["Debility from loss of fluids","Periodicity — every other day","Tympanitic distension","Hypersensitivity of all senses","Never well since haemorrhage"],
    mind:["Fixed ideas","Theorizes, plans great things","Hypersensitive to touch","Indolent"],
    worse:["Touch","Alternate days","Cold","After eating"], better:["Warmth","Hard pressure","Open air"],
    comp:["Ferrum","Calcarea Phos"], anti:["Arsenicum","Nux Vomica"] },
  { name:"Colocynthis", abbr:"Coloc.", cat:"plant", const:"Anger causing violent cramping pains",
    keys:["Violent colic — must bend double","Ailments from indignation, anger","Better hard pressure","Better bending double","Neuralgic pains"],
    mind:["Indignation, anger","Reserved displeasure","Impatient"],
    worse:["Anger","After eating","Damp cold"], better:["Bending double","Hard pressure","Heat"],
    comp:["Causticum","Mercurius"], anti:["Coffea","Staphysagria"] },
  { name:"Conium Maculatum", abbr:"Con.", cat:"plant", const:"Ascending paralysis, suppressed sexual desire",
    keys:["Ascending paralysis","Hardening of glands","Dizziness from turning head","Suppressed or excessive sexual desire","Old people or widows"],
    mind:["Mental weakness","Indifferent","Depressed","Memory poor"],
    worse:["Lying down","Turning head","Motion"], better:["Letting parts hang down","Pressure","Fasting"],
    comp:["Baryta Carb","Silica"], anti:["Coffea","Nux Vomica"] },
  { name:"Drosera", abbr:"Dros.", cat:"plant", const:"Whooping cough, persistent dry bark cough",
    keys:["Whooping cough — spasmodic","Cough worse after midnight","Laryngeal tuberculosis","Deep hoarse voice","Holds chest while coughing"],
    mind:["Restless","Suspicious","Persevering despite obstacles"],
    worse:["After midnight","Lying down","Warmth","Talking"], better:["Open air","Sitting up"],
    comp:["Nux Vomica","Pulsatilla"], anti:["Camphor"] },
  { name:"Euphrasia", abbr:"Euph.", cat:"plant", const:"Eye complaints with profuse acrid lachrymation",
    keys:["Acrid, burning tears","Bland nasal discharge — opposite of Allium Cepa","Photophobia","Catarrhal conditions of eyes","Involuntary blinking"],
    mind:["Few mental symptoms"],
    worse:["Sunlight","Wind","Indoors"], better:["Darkness","Open air","Coffee"],
    comp:["Allium Cepa","Pulsatilla"], anti:["Camphor"] },
  { name:"Ferrum Metallicum", abbr:"Ferr.", cat:"mineral", const:"Anaemia with false plethora, weakness",
    keys:["Anaemia — pale yet flushes easily","Weakness with false plethora","Haemorrhages bright red","Worse exertion, better gentle motion","Noise intolerance"],
    mind:["Contradiction angers them","Obstinate","Oversensitive to noise"],
    worse:["Night","Rest","Cold"], better:["Slow gentle motion","Walking slowly"],
    comp:["China","Calcarea Phos"], anti:["Arsenicum","China"] },
  { name:"Gelsemium", abbr:"Gels.", cat:"plant", const:"Anticipatory paralytic weakness, dullness",
    keys:["Anticipation — stage fright, exam fear","Paralytic weakness — heavy eyelids","Dullness, trembling","Wants to be left alone","Chills up and down spine"],
    mind:["Dullness, mental torpor","Anticipatory anxiety","Wants to be alone","Stage fright"],
    worse:["Emotion","Excitement","Damp","Before storms"], better:["Urination","Stimulants","Open air","Motion"],
    comp:["Baptisia","Ipecac"], anti:["Coffea","China"] },
  { name:"Graphites", abbr:"Graph.", cat:"mineral", const:"Unhealthy skin, oozing honey-like discharge",
    keys:["Skin cracks oozing honey-like discharge","Worse warmth","Constipation with large hard knotty stools","Timid, irresolute","Unhealthy skin — every injury suppurates"],
    mind:["Timid, irresolute","Cautious","Weeps from music","Fat, chilly, constipated"],
    worse:["Warmth","Night","During menses"], better:["Wrapping up","Dark","Open air"],
    comp:["Lycopodium","Pulsatilla"], anti:["Arsenicum","Nux Vomica"] },
  { name:"Hepar Sulphuris", abbr:"Hep.", cat:"mineral", const:"Extremely sensitive, angry, suppurations",
    keys:["Extreme hypersensitivity","Suppurations — stinking like old cheese","Croup with rattling","Cold air aggravates","Splinter sensation"],
    mind:["Irritable, impulsive","Violent impulses","Hypersensitive to pain, cold, touch","Hasty speech"],
    worse:["Cold dry wind","Touch","Night"], better:["Warmth","Wrapping","Damp weather"],
    comp:["Silicea","Nitric Acid"], anti:["Camphor","Belladonna"] },
  { name:"Hyoscyamus", abbr:"Hyos.", cat:"plant", const:"Jealousy, mania, loquacity, exhibitionism",
    keys:["Loquacity — jumps from subject to subject","Jealousy, suspicion","Picks at bedclothes","Obscene behaviour, exposes self","Convulsions without fever"],
    mind:["Jealousy","Loquacity","Suspicion","Obscene","Delirium"],
    worse:["Night","Emotions","Touch"], better:["Stooping","Lying down"],
    comp:["Belladonna","Stramonium"], anti:["Belladonna","Nux Vomica"] },
  { name:"Kali Carbonicum", abbr:"Kali-c.", cat:"mineral", const:"Conscientious, rigid, 2-4 AM aggravation",
    keys:["2–4 AM aggravation","Stitching pains","Bag-like swelling between eyelids","Backache after childbirth","Rigid, dogmatic personality"],
    mind:["Rigid, conservative","Fears death, future","Never alone","Conscientious"],
    worse:["2–4 AM","Cold","After coition","Lying on painful side"], better:["Warmth","Moving about","Daytime"],
    comp:["Carbo Veg","Phosphorus"], anti:["Camphor","Coffea"] },
  { name:"Kali Phosphoricum", abbr:"Kali-p.", cat:"mineral", const:"Nerve exhaustion, brain fatigue",
    keys:["Nervous exhaustion — students, businessmen","Asafoetida-like odour","Brain fatigue","Anxiety, fear","Insomnia from worry"],
    mind:["Nervous exhaustion","Anxiety","Brain fatigue","Homesickness","Fear of crowds"],
    worse:["Excitement","Mental exertion","Cold"], better:["Warmth","Rest","Nourishment"],
    comp:["Zincum","Magnesia Phos"], anti:["Coffea"] },
  { name:"Ledum Palustre", abbr:"Led.", cat:"plant", const:"Puncture wounds, ascending coldness",
    keys:["Puncture wounds — first remedy","Cold applications relieve","Ascending rheumatism","Black eye from injury","Worse warmth of bed"],
    mind:["Discontented","Misanthropy","Intoxicated feeling"],
    worse:["Warmth","Night","Motion"], better:["Cold applications","Rest"],
    comp:["Apis","Sepia"], anti:["Camphor","Rhus Tox"] },
  { name:"Magnesia Phosphorica", abbr:"Mag-p.", cat:"mineral", const:"Neuralgic cramping pains, better heat",
    keys:["Cramping pains relieved by heat","Writer's cramp","Radiating neuralgic pains","Flatulence","Better bending double"],
    mind:["Few mental symptoms","Laments about pain"],
    worse:["Cold","Night","Touch","Right side"], better:["Heat","Pressure","Bending double"],
    comp:["Kali Phos","Silica"], anti:["Belladonna"] },
  { name:"Medorrhinum", abbr:"Med.", cat:"nosode", const:"Sycotic miasm, intense, extremes of behaviour",
    keys:["Sycotic miasm remedy","Intense emotions — extremes","Better at seaside","Worse from sunset to sunrise","Wild, reckless behaviour in children"],
    mind:["Intense","Wild, reckless","Time passes slowly","Anticipatory anxiety","Love of animals"],
    worse:["Inland","Sunrise to sunset","Heat"], better:["Seaside","Damp weather","Lying on face"],
    comp:["Natrum Sulph","Thuja"], anti:["Thuja"] },
  { name:"Mercurius Solubilis", abbr:"Merc.", cat:"mineral", const:"Profuse offensive discharges, night aggravation",
    keys:["Profuse offensive sweating without relief","Creeping chilliness","Tongue shows imprint of teeth","Worse at night","Trembling — mercurial tremor"],
    mind:["Slow in answering","Suspicious","Sensitive to heat and cold equally","Impulse to harm"],
    worse:["Night","Warmth of bed","Sweat","Wet weather"], better:["Moderate temperature","Rest"],
    comp:["Belladonna","Hepar Sulph"], anti:["Hepar","China","Sulphur"] },
  { name:"Mezereum", abbr:"Mez.", cat:"plant", const:"Neuralgic pains with thick crusts, worse cold air",
    keys:["Violent neuralgic pains after herpes zoster","Thick leather-like crusts on head","Worse cold air, warm food","Bone pains at night","Eczema with thick pus"],
    mind:["Hypochondriac","Indifferent","Desires to be in open air"],
    worse:["Cold air","Night","Warmth of bed"], better:["Open air","Motion"],
    comp:["Arsenicum","Mercurius"], anti:["Kali Iod"] },
  { name:"Natrum Carbonicum", abbr:"Nat-c.", cat:"mineral", const:"Selfless, devoted, sensitive to music and sun",
    keys:["Sun causes headache","Weakness from exertion","Sensitive to music","Devoted, self-sacrificing","Debility"],
    mind:["Selfless","Anxiety from music","Devoted to family","Easily discouraged"],
    worse:["Sun","Summer heat","Music","Mental exertion"], better:["Motion","Eating","Dark"],
    comp:["Pulsatilla","Sepia"], anti:["Arsenicum"] },
  { name:"Nitric Acid", abbr:"Nit-ac.", cat:"mineral", const:"Splinter pains, unforgiving, malignant tendency",
    keys:["Splinter-like pains","Unforgiving — holds grudges","Warts — large, bleeding","Fissures at muco-cutaneous junctions","Anxiety about health"],
    mind:["Unforgiving","Malicious","Anxiety about health","Irritable"],
    worse:["Night","Touch","Cold"], better:["Mild weather","Riding in carriage"],
    comp:["Arsenicum","Calcarea"], anti:["Milk","Hepar Sulph"] },
  { name:"Nux Moschata", abbr:"Nux-m.", cat:"plant", const:"Extreme drowsiness, dryness, fainting",
    keys:["Extreme drowsiness — falls asleep while talking","Dryness without thirst","Fainting spells","Bloating after eating","Variable moods"],
    mind:["Changeable moods","Absent-minded","Laughing and crying alternately"],
    worse:["Cold damp wind","After eating"], better:["Warmth","Dry weather"],
    comp:["Pulsatilla","Ignatia"], anti:["Coffea"] },
  { name:"Opium", abbr:"Op.", cat:"plant", const:"Stupor, painlessness, absence of reaction",
    keys:["Painlessness of complaints","Stupor, insensibility","Constipation — round black balls","Never well since fright","Lack of vital reaction"],
    mind:["Stupor","Painlessness","Wants nothing","Happy, delirious","Delirium tremens"],
    worse:["Heat","During sleep","Fright"], better:["Cold","Constant walking"],
    comp:["Belladonna","Hyoscyamus"], anti:["Belladonna","Ipecac","Coffea"] },
  { name:"Petroleum", abbr:"Petr.", cat:"mineral", const:"Skin cracks in winter, motion sickness",
    keys:["Deep cracks in skin — bleed","Nausea from motion (car, sea)","Worse in winter","Occipital headache","Chilly patient"],
    mind:["Irritable","Confused about identity","Rage"],
    worse:["Winter","Damp","Motion"], better:["Warm","Dry weather"],
    comp:["Sulphur","Psorinum"], anti:["Nux Vomica","Cocculus"] },
  { name:"Platina", abbr:"Plat.", cat:"mineral", const:"Pride, contempt, sexual excess, haughtiness",
    keys:["Haughtiness — contempt for others","Nymphomania","Excessive sexual desire","Parts feel large and numb","Mental symptoms with disappearance of physical"],
    mind:["Arrogance","Contempt","Nymphomania","Delusion — she is of great rank"],
    worse:["Touch","Evening","Standing"], better:["Motion","Open air"],
    comp:["Ignatia","Palladium"], anti:["Pulsatilla"] },
  { name:"Psorinum", abbr:"Psor.", cat:"nosode", const:"Psoric miasm, hopeless, filthy, cold",
    keys:["Hopelessness — doesn't believe he will recover","Skin: dirty, filthy-smelling despite washing","Worse from cold","Hungry at night","Whole body itching worse from warmth"],
    mind:["Hopeless","Despairing","Fear of poverty","Extreme chilliness"],
    worse:["Cold air","Open air","Change of weather"], better:["Heat","Warm clothing","Eating"],
    comp:["Sulphur","Tuberculinum"], anti:["Coffea","Sulphur"] },
  { name:"Ruta Graveolens", abbr:"Ruta", cat:"plant", const:"Bruised bones, eye strain, tendons",
    keys:["Bruised feeling in bones and periosteum","Eye strain from overuse","Tendons and cartilages","Restless","Wrists and ankles sprained"],
    mind:["Dissatisfied","Quarrelsome","Anxious"],
    worse:["Cold wet weather","Lying","Overexertion"], better:["Warmth","Motion"],
    comp:["Arnica","Calcarea Phos"], anti:["Camphor"] },
  { name:"Silica", abbr:"Sil.", cat:"mineral", const:"Lack of grit, pushes out foreign bodies",
    keys:["Lack of confidence — yielding yet stubborn","Pushes out foreign bodies","Slow suppuration","Profuse sweating of feet and head","Chilly, refined, impeccable"],
    mind:["Yielding yet obstinate","Lack of confidence","Anxious","Fixed ideas"],
    worse:["Cold","Draft","Suppressed sweat"], better:["Warmth","Wrapping head"],
    comp:["Fluoric Acid","Thuja"], anti:["Hepar Sulph","Camphor"] },
  { name:"Spigelia", abbr:"Spig.", cat:"plant", const:"Neuralgic pains radiating, cardiac affections",
    keys:["Severe neuralgic pains — left-sided","Heart affections with palpitations","Stitching pains — worse motion","Strabismus","Worms in children"],
    mind:["Timid","Fear of pointed things","Restless"],
    worse:["Motion","Touch","Cold","Morning"], better:["Sunset","Lying on right side","Still"],
    comp:["Arsenicum","Aconite"], anti:["Coffea","Pulstilla"] },
  { name:"Spongia Tosta", abbr:"Spong.", cat:"animal", const:"Croup, cough like sawing wood, cardiac",
    keys:["Croup — cough like sawing through wood","Awakens in fright, suffocation","Anxiety before cough","Worse before midnight","Hyperthyroid goitre"],
    mind:["Anxiety","Fear of death during cough","Frightened look"],
    worse:["Before midnight","Ascending","Warmth"], better:["Eating","Warm drinks","Bending head forward"],
    comp:["Aconite","Hepar Sulph"], anti:["Arsenicum"] },
  { name:"Staphysagria", abbr:"Staph.", cat:"plant", const:"Suppressed anger, ailments from indignation",
    keys:["Ailments from suppressed anger, humiliation","Sweet disposition — never gets angry, then explodes","Wounds from sharp instruments","Stye on eyelid","Cystitis after catheterisation"],
    mind:["Suppressed indignation","Sweet externally, seething inside","Romantic sensitivity","Thrown objects when angry"],
    worse:["Indignation","Suppressed emotions","Touch"], better:["Warmth","Rest","Breakfast"],
    comp:["Causticum","Ignatia"], anti:["Camphor"] },
  { name:"Stramonium", abbr:"Stram.", cat:"plant", const:"Terror, violence, horror of darkness and water",
    keys:["Terror — abandoned","Loquacious — talks, sings, prays continuously","Fear of darkness and water","Violent mania","Convulsions with consciousness retained"],
    mind:["Terror of being abandoned","Violent","Fear of dark, water","Loquacity","Religious frenzy"],
    worse:["Darkness","Being alone","Glittering objects"], better:["Light","Company","Warmth"],
    comp:["Belladonna","Hyoscyamus"], anti:["Belladonna","Tabacum"] },
  { name:"Thuja Occidentalis", abbr:"Thuj.", cat:"plant", const:"Sycotic miasm, fixed ideas, warts",
    keys:["Warts — seedy, large, pedunculated","Sycotic miasm remedy","Fixed ideas — body is fragile","Ailments after vaccination","Perspires only on uncovered parts"],
    mind:["Fixed ideas","Hurried","Secretive","Ailments from vaccination"],
    worse:["Cold damp","Night","3 AM, 3 PM"], better:["Warmth","Dry weather"],
    comp:["Natrum Sulph","Medorrhinum"], anti:["Camphor","Mercurius"] },
  { name:"Tuberculinum", abbr:"Tub.", cat:"nosode", const:"Psoric-sycotic miasm, restlessness, desire travel",
    keys:["Desire for change and travel","Dissatisfied — wants something but doesn't know what","Tall, slender, narrow chest","Recurrent colds, tonsillitis","Restless, active mind"],
    mind:["Desire for change","Restlessness","Irritable in morning","Cruel to animals (children)"],
    worse:["Cold damp","Before storms","Night"], better:["Open air","Dry cold weather"],
    comp:["Psorinum","Calcarea"], anti:["Psorinum"] },
  { name:"Veratrum Album", abbr:"Verat.", cat:"plant", const:"Collapse with cold sweat, mania with ambition",
    keys:["Cold sweat on forehead","Collapse with extreme coldness","Violent mania — prays, howls","Craves cold water — vomited immediately","Cutting pains followed by exhaustion"],
    mind:["Megalomania","Mania with religious frenzy","Haughty","Talks of rank"],
    worse:["Cold","Night","Wet cold"], better:["Warmth","Hot drinks","Walking"],
    comp:["Arsenicum","China"], anti:["Arsenicum","China"] },
  { name:"Zincum Metallicum", abbr:"Zinc.", cat:"mineral", const:"Nerve exhaustion, fidgety feet, suppressed eruptions",
    keys:["Fidgety feet — constant motion","Brain fatigue from over-study","Suppressed eruptions causing brain symptoms","Weakness, trembling","Cannot bear wine"],
    mind:["Brain fatigue","Restless","Repetition of words in answer","Slow perception"],
    worse:["Suppressions","Wine","After menses"], better:["Motion","Open air","Eating"],
    comp:["Calcarea","Silica"], anti:["Hepar","Nux Vomica"] },
  { name:"Calcarea Phosphorica", abbr:"Calc-p.", cat:"mineral", const:"Delayed development, growing pains, anaemia",
    keys:["Delayed teething and fontanels closing","Growing pains","Anaemia in adolescents","Desire to travel","School headache in children"],
    mind:["Peevish","Desire to travel","Discontent"],
    worse:["Cold damp","Teething","Mental exertion"], better:["Warmth","Summer","Dry weather"],
    comp:["Silica","Sulphur"], anti:["Camphor","Rhus Tox"] },
  { name:"Calcarea Sulphurica", abbr:"Calc-s.", cat:"mineral", const:"Suppurations, yellowish discharges",
    keys:["Suppurations — one opening not healing","Yellow pus — thick","Skin diseases with pus","Unhealthy skin","Acne with yellow discharge"],
    mind:["Jealousy","Irritable"],
    worse:["In heated room"], better:["Open air","Bathing"],
    comp:["Silica","Sulphur"], anti:["Camphor"] },
  { name:"Cantharis", abbr:"Canth.", cat:"animal", const:"Violent inflammation, burning, UTI",
    keys:["Violent burning — urinary tract","Intolerable urging to urinate","Burns everywhere — skin, mucosa","Priapism","Mania with sexual excitement"],
    mind:["Violent delirium","Sexual mania","Increased sexual desire"],
    worse:["Urination","Coffee","Cold water"], better:["Warmth","Rest"],
    comp:["Apis","Causticum"], anti:["Camphor","Pulsatilla"] },
  { name:"Carbo Vegetabilis", abbr:"Carb-v.", cat:"mineral", const:"Vital collapse, air hunger, cold breath",
    keys:["Vital collapse — cold breath, cold surface but desires fanning","Air hunger — must be fanned","Venous stasis","Flatulence with belching relief","Never well since severe illness"],
    mind:["Indifference","Fear of dark","Slowness of thought"],
    worse:["Warmth","Fatty food","Evening and night"], better:["Belching","Fanning","Cold air"],
    comp:["Kali Carb","Phosphorus"], anti:["Arsenicum","Camphor"] },
  { name:"Ipecacuanha", abbr:"Ip.", cat:"plant", const:"Persistent nausea, clean tongue, haemorrhage",
    keys:["Persistent nausea — not relieved by vomiting","Clean tongue despite nausea","Bright red haemorrhage","Rattling cough","Disgust for food"],
    mind:["Disdainful","Irritable","Holds on to desires of childhood"],
    worse:["Periodically","Veal","Moist warm wind"], better:["Open air","Rest","Pressure"],
    comp:["Cuprum","Arsenicum"], anti:["Arsenicum","China"] },
  { name:"Lycopus Virginicus", abbr:"Lyc-v.", cat:"plant", const:"Cardiac, thyroid, haemoptysis",
    keys:["Cardiac hypertrophy","Hyperthyroidism","Haemoptysis","Palpitations with dyspnoea","Exophthalmos"],
    mind:["Anxiety","Restlessness"],
    worse:["Exertion","Night"], better:["Rest"],
    comp:["Crataegus","Digitalis"], anti:[""] },
  { name:"Natrum Sulphuricum", abbr:"Nat-s.", cat:"mineral", const:"Sycotic miasm, humidity, head injuries",
    keys:["Never well since head injury","Worse damp, wet weather","Sycotic miasm remedy","Suicidal thoughts","Liver complaints"],
    mind:["Suicidal — must hold himself back","Serious","Worse from music","Ailments from head injury"],
    worse:["Damp","Wet weather","Night","Lying on left side"], better:["Dry weather","Changing position"],
    comp:["Medorrhinum","Thuja"], anti:["Camphor"] },
  { name:"Rhododendron", abbr:"Rhod.", cat:"plant", const:"Rheumatism before storms, testicle affections",
    keys:["Rheumatism worse before storms","Orchitis — testes shrink","Must move to relieve","Toothache before storms","Forgetfulness"],
    mind:["Forgetful","Fears thunderstorm"],
    worse:["Before storms","Cold wet weather","Rest"], better:["After storms","Warmth","Motion"],
    comp:["Bryonia","Rhus Tox"], anti:["Camphor"] },
  { name:"Sabadilla", abbr:"Sabad.", cat:"plant", const:"Hay fever, sneezing fits, chilly",
    keys:["Sneezing — continuous fits","Lachrymation from sneezing","Extremely chilly","Worms","Delusion of serious illness"],
    mind:["Nervous","Easily startled","Delusion of terrible disease"],
    worse:["Cold air","Odours","Moon"], better:["Warmth","Warm food","Swallowing"],
    comp:["Gelsemium","Lycopodium"], anti:["Cognacs","Vinegar"] },
  { name:"Sarsaparilla", abbr:"Sars.", cat:"plant", const:"Urinary complaints, skin, emaciation",
    keys:["Intolerable pain at close of urination","Urine dribbles while sitting","Sand in urine","Severe emaciation","Skin rough, dirty"],
    mind:["Sensitive to contradiction"],
    worse:["End of urination","Cold damp"], better:["Standing to urinate","Uncovering"],
    comp:["Natrum Mur","Sepia"], anti:["Bell","Mercurius"] },
  { name:"Secale Cornutum", abbr:"Sec.", cat:"fungus", const:"Burning, gangrene, thin patients, worse warmth",
    keys:["Burning sensation — wants cold even in cold conditions","Gangrene — dry","Thin, cachectic women","Worse warmth, covers","Painless paralysis"],
    mind:["Anxiety","Violent","Mania"],
    worse:["Warmth","Covers","During menses"], better:["Cold air","Rubbing","Motion"],
    comp:["Arsenicum","Carbo Veg"], anti:["Camphor","Opium"] },
  { name:"Stannum Metallicum", abbr:"Stan.", cat:"mineral", const:"Weakness from coughing, gradual weakness",
    keys:["Extreme weakness from cough","Slow onset of symptoms","Hoarseness — worse talking","Mucus — sweet, salty, green","Empty, gone feeling in chest"],
    mind:["Sad","Hopeless","Cries before coughing"],
    worse:["Using voice","Lying on right side","Warm drinks"], better:["Lying on abdomen","Hard pressure"],
    comp:["Pulsatilla","Silica"], anti:["Pulsatilla"] },
  { name:"Syphilinum", abbr:"Syph.", cat:"nosode", const:"Syphilitic miasm, worse at night, bone pains",
    keys:["Syphilitic miasm remedy","Bone pains worse at night","Nocturnal aggravation of all symptoms","Memory loss","Destructive tendencies"],
    mind:["Memory loss","Hopeless","Insanity"],
    worse:["Night","Sunset to sunrise","Heat"], better:["Sunrise","Sea","Bathing"],
    comp:["Mercurius","Nitric Acid"], anti:["Mercurius","Kali Iod"] },
  { name:"Coffea Cruda", abbr:"Coff.", cat:"plant", const:"Hypersensitivity from joy, sleeplessness",
    keys:["Sleeplessness from joy, good news","Oversensitivity to pain","Palpitations from joy","Toothache relieved by ice water","Mind full of ideas at night"],
    mind:["Oversensitivity to everything","Mind full of ideas","Cannot sleep from mental activity","Too much joy"],
    worse:["Strong emotions","Noise","Open air","Night"], better:["Warmth","Lying down","Ice"],
    comp:["Aconite","Chamomilla"], anti:["Nux Vomica","Chamomilla"] },
  { name:"Crotalus Horridus", abbr:"Crot-h.", cat:"animal", const:"Right-sided, haemorrhages, malignancy",
    keys:["Right-sided remedy","Haemorrhagic tendency — blood does not clot","Septic states","Alcoholism — delirium tremens","Malignant conditions"],
    mind:["Loquacity","Weeping","Religious"],
    worse:["Right side","Open air","Morning"], better:["Rest"],
    comp:["Lachesis","Arsenicum"], anti:["Camphor","Arsenicum"] },
  { name:"Cuprum Metallicum", abbr:"Cupr.", cat:"mineral", const:"Spasms, cramps, epilepsy",
    keys:["Violent spasms and cramps","Begins in fingers and toes","Epilepsy — begins with aura in knees","Whooping cough — spasmodic","Metallic taste"],
    mind:["Anxiety before spasm","Malicious","Stubborn"],
    worse:["Vomiting","Emotional excitement","Touch"], better:["Cold drinks","Pressure","Perspiration"],
    comp:["Calc","Ipecac"], anti:["Camphor","Dulcamara"] },
  { name:"Dulcamara", abbr:"Dulc.", cat:"plant", const:"Ailments from cold damp, seasonal changes",
    keys:["Ailments from cold damp weather","Every cold spell causes relapse","Urticaria in cold damp","Warts on face, hands","Autumn colds"],
    mind:["Irritable","Impatient","Confusion"],
    worse:["Cold damp","Change to cold weather","Night"], better:["Moving about","Warmth"],
    comp:["Calcarea","Rhus Tox"], anti:["Camphor","Belladonna"] },
  { name:"Fluoric Acid", abbr:"Fl-ac.", cat:"mineral", const:"Tissue destruction, indifference, sexuality",
    keys:["Varicose veins","Fistulae, ulcers","Increased sexual desire","Indifference to family","Worse warmth"],
    mind:["Indifference to loved ones","Increased sexual desire","Elated, full of plans"],
    worse:["Warmth","Morning"], better:["Cold","Short sleep"],
    comp:["Silica","Phosphorus"], anti:["Silica"] },
  { name:"Hamamelis", abbr:"Ham.", cat:"plant", const:"Venous haemorrhage, varicose veins",
    keys:["Venous haemorrhage — passive, dark","Varicose veins with soreness","Haemorrhoids","Haemoptysis","Bruised soreness in affected parts"],
    mind:["Despondent"],
    worse:["Warmth","Moisture"], better:["Lying","Coolness"],
    comp:["Ferrum","Aconite"], anti:["Arnica"] },
  { name:"Iodium", abbr:"Iod.", cat:"mineral", const:"Emaciation despite eating, hyperthyroid",
    keys:["Emaciation — eats voraciously but emaciates","Hyperthyroidism","Must be busy — anxiety when quiet","Glandular enlargement then atrophy","Hot patient"],
    mind:["Anxiety when quiet","Must be busy","Fear of people","Impulse to violence"],
    worse:["Warmth","Rest","Right side"], better:["Motion","Cool","Eating"],
    comp:["Lycopodium","Phosphorus"], anti:["Starch","Sulphur"] },
  { name:"Kalium Bichromicum", abbr:"Kali-bi.", cat:"mineral", const:"Stringy mucus, ulcers with punched-out edges",
    keys:["Stringy, tough, ropy mucus","Ulcers — punched out edges","Sinusitis with pressure at root of nose","Wandering pains — move rapidly","Seasonable complaints"],
    mind:["Materialistic","Loves only family"],
    worse:["Cold","2–3 AM","Beer","Hot weather"], better:["Heat","Motion","Pressure"],
    comp:["Arsenicum","Brom"], anti:["Arsenicum","Lachesis"] },
  { name:"Lilium Tigrinum", abbr:"Lil-t.", cat:"plant", const:"Pelvic congestion, hurried, heart affection",
    keys:["Dragging sensation in pelvis — women","Wild hurry","Palpitation — fluttering","Hatred of others","Heart and uterine symptoms combined"],
    mind:["Hurried","Wild feeling","Fear of insanity","Irritable","Religious despondency"],
    worse:["Warm room","Console"], better:["Cool air","Occupation","Walking fast"],
    comp:["Murex","Sepia"], anti:["Helon"] },
  { name:"Lobelia Inflata", abbr:"Lob.", cat:"plant", const:"Asthma with nausea, extreme weakness",
    keys:["Asthma with nausea","Weakness in epigastrium","Morning sickness","Relieves tobacco withdrawal","Slow pulse"],
    mind:["Fear of death","Anxiety"],
    worse:["Tobacco","Cold","Motion"], better:["Rapid walking","Evening"],
    comp:["Ipecac","Tabacum"], anti:["Tabacum","Nux Vomica"] },
  { name:"Magnesia Carbonica", abbr:"Mag-c.", cat:"mineral", const:"Sour, unwanted child, milk intolerance",
    keys:["Everything tastes sour","Milk disagrees — sour stools in nursing children","Restless nights","Sensitive to least draught","Neglected, unwanted feeling"],
    mind:["Restless at night","Sensitive","Feels unloved"],
    worse:["Night","3 AM","Rest","Milk"], better:["Motion","Open air","Warmth"],
    comp:["Silica","Pulsatilla"], anti:["Acids","China"] },
  { name:"Murex Purpurea", abbr:"Murx.", cat:"animal", const:"Sexual excitement in women, uterine complaints",
    keys:["Sexual excitement from least contact","Uterine complaints — dysmenorrhoea","Violent sexual desire","Must cross legs","Pelvic pain"],
    mind:["Sexually excited easily","Depressed","Lascivious dreams"],
    worse:["Touch","Lying","Mental exertion"], better:["Rest","Sea"],
    comp:["Sepia","Lilium Tig"], anti:["Belladonna"] },
  { name:"Oleander", abbr:"Olnd.", cat:"plant", const:"Skin, paralysis, vertigo",
    keys:["Vertigo — looking at passing objects","Paralytic weakness","Skin — perspiration","Inability to digest milk","Itching worse warmth"],
    mind:["Absent-minded","Vexed","Irritable"],
    worse:["Undressing","Eating","Night"], better:["Motion"],
    comp:["Calad","Cann-s"], anti:["Coffea"] },
  { name:"Oxalic Acid", abbr:"Ox-ac.", cat:"mineral", const:"Hyperoxaluria, pains worse thinking of them",
    keys:["Pains worse when thinking of them","Oxalate stones","Spinal pains","Numbness extremities","Heart palpitations"],
    mind:["Pain worse when thought about"],
    worse:["Thinking of symptoms","Touch","Motion"], better:["Coffee"],
    comp:["Argentum Nit"], anti:[""] },
  { name:"Phosphoric Acid", abbr:"Ph-ac.", cat:"mineral", const:"Debility from grief, mental first then physical",
    keys:["Debility — mental then physical","Ailments from grief, disappointed love","Apathy, indifference","Copious watery urine","Growing pains in youth"],
    mind:["Apathy","Indifference — even to family","Grief-stricken","Dull, listless"],
    worse:["Loss of fluids","Grief","Cold"], better:["Warmth","Short sleep"],
    comp:["China","Natrum Mur"], anti:["Coffea","China"] },
  { name:"Picric Acid", abbr:"Pic-ac.", cat:"mineral", const:"Burning in spine, brain fatigue, sexual excess",
    keys:["Burning in spine","Brain fatigue — from sexual excess","Priapism","Inability to exert mind","Weight in back"],
    mind:["Brain fatigue","Inability to think","Indifference"],
    worse:["Least exertion","Wet weather","Emotions"], better:["Rest","Cool air"],
    comp:["Gels","Nux Vomica"], anti:[""] },
  { name:"Plumbum Metallicum", abbr:"Plb.", cat:"mineral", const:"Progressive paralysis, colic, emaciation",
    keys:["Progressive paralysis — extensor muscles","Severe colic — drawing navel to spine","Emaciation","Wrist drop","Yellow, dry skin"],
    mind:["Memory loss","Slow comprehension","Fear of being murdered"],
    worse:["Motion","Night"], better:["Hard pressure","Rubbing"],
    comp:["Arsenicum","Alum"], anti:["Alum","Petrol"] },
  { name:"Sabina", abbr:"Sabin.", cat:"plant", const:"Arthritic joints, threatened abortion, haemorrhage",
    keys:["Threatened abortion at 3rd month","Haemorrhage — bright red with clots","Pains from sacrum to pubis","Arthritic gout","Warts with itching"],
    mind:["Music unbearable","Nervous"],
    worse:["Least motion","Warm room","Music"], better:["Cool fresh air"],
    comp:["Thuja","Crocus"], anti:["Pulsatilla"] },
  { name:"Scilla Maritima", abbr:"Scil.", cat:"plant", const:"Cardiac dropsy, cough, urinary",
    keys:["Copious watery urine","Cough — exhausting","Dropsy — cardiac, renal","Sneezing with cough","Involuntary urination while coughing"],
    mind:["Anxiety","Irritable"],
    worse:["Morning","Cold air","Motion"], better:["Rest","Warmth"],
    comp:["Digitalis","Arsenicum"], anti:["Camphor"] },
  { name:"Senega", abbr:"Seneg.", cat:"plant", const:"Rattling mucus, old people, eye",
    keys:["Rattling in chest — can't expectorate","Old people with catarrh","Eye — opacity of cornea","Tenacious mucus","Violent sneezing with mucus"],
    mind:["Irritable"],
    worse:["Cold","Motion"], better:["Bending head back","Warmth"],
    comp:["Amm carb","Arsenicum"], anti:[""] },
  { name:"Tabacum", abbr:"Tab.", cat:"plant", const:"Motion sickness, deathly nausea, collapse",
    keys:["Deathly nausea — pale, cold sweat","Violent palpitations","Motion sickness","Sudden collapse","Intermittent pulse"],
    mind:["Despairing during motion sickness","Anxious"],
    worse:["Open eyes","Smell of tobacco","Pregnancy"], better:["Uncovering abdomen","Cold fresh air"],
    comp:["Nux Vomica","Petroleum"], anti:["Arsenicum","Camphora"] },
  { name:"Tellurium", abbr:"Tell.", cat:"mineral", const:"Back injury, offensive discharges, herpes",
    keys:["Spinal affections after injury","Herpes zoster","Offensive discharges — fishy","Back sensitive to touch","Ringworm"],
    mind:["Forgetful","Absorbed"],
    worse:["Night","Lying on back","Cold water"], better:["Daytime"],
    comp:["Silica","Sulphur"], anti:[""] },
  { name:"Urtica Urens", abbr:"Urt-u.", cat:"plant", const:"Urticaria, burns, gout, decreased milk",
    keys:["Urticaria — violent itching and burning","Burns — first degree","Decreased milk in nursing mothers","Gout","Rheumatic pains"],
    mind:["Few mental symptoms"],
    worse:["Snow","Cold wet air","Touch"], better:["Rubbing"],
    comp:["Apis","Dulcamara"], anti:["Dock"] },
  { name:"Valeriana", abbr:"Valer.", cat:"plant", const:"Hysteria, changeability, nervous excitability",
    keys:["Hysterical disposition","Oversensitivity — pain, smell, touch","Changeable symptoms","Sensation of thread in throat","Sci atic pain"],
    mind:["Hysteria","Changeable mood","Exalted","Hallucinations at night"],
    worse:["Night","Standing","Rest"], better:["Motion","Warmth"],
    comp:["Ignatia","Pulsatilla"], anti:["Pulsatilla"] },
];

// ─── ORGANON — ALL MAJOR APHORISMS ──────────────────────────────────────────
const organon = [
  {n:1, t:"The physician's high and only mission is to restore the sick to health, to cure, as it is termed.", topic:"Mission of the Physician"},
  {n:2, t:"The highest ideal of cure is rapid, gentle and permanent restoration of health on easily comprehensible principles.", topic:"Ideal of Cure"},
  {n:3, t:"If the physician clearly perceives what is to be cured in diseases and what is curative in medicines, and rightly adapts the curative to the morbid, recovery must result.", topic:"Physician's Triple Knowledge"},
  {n:6, t:"The unprejudiced observer recognises nothing in every individual disease except the changes in the condition of the body and mind perceptible to the senses. These morbid phenomena are the disease itself.", topic:"Disease Definition"},
  {n:7, t:"As we can perceive nothing but the morbid symptoms, it must be the symptoms alone by which the disease demands and points to the remedy suited to it.", topic:"Symptoms Guide Prescription"},
  {n:9, t:"In the healthy condition of man, the spiritual vital force animates the material body and retains all its parts in admirable, harmonious, vital operation.", topic:"Vital Force — Health"},
  {n:10, t:"The material organism without the vital force is incapable of sensation or function; it derives all sensation and performs all functions of life solely by means of the immaterial vital force.", topic:"Vital Force — Role"},
  {n:11, t:"When a person falls ill, it is only the spiritual, self-acting vital force everywhere present in the organism that is primarily deranged by the dynamic influence of a morbific agent.", topic:"Vital Force — Disease"},
  {n:12, t:"It is the morbidly affected vital energy alone that produces diseases. The visible symptoms express all the internal change — the whole disease.", topic:"Vital Force Expresses Disease"},
  {n:13, t:"Therefore disease (excluding surgical cases) is not a separate thing from the living whole, from the organism and its animating vital force.", topic:"Disease — Not Separate Entity"},
  {n:14, t:"There is in the interior of man nothing morbid that is curable and no invisible morbid alteration that is not indicated by symptoms.", topic:"All Disease Has Symptoms"},
  {n:15, t:"The suffering of the morbidly deranged, spirit-like vital force and the symptoms produced thereby constitute one and the same thing.", topic:"Symptoms = Vital Force Derangement"},
  {n:16, t:"Our vital force, as a spirit-like dynamis, cannot be attacked and affected by injurious influences except by spirit-like (dynamic) power.", topic:"Dynamic Nature of Disease"},
  {n:17, t:"Only the disappearance of all morbid symptoms shows that we have restored the health of the patient — that the whole disease has been removed.", topic:"Cure — Complete Symptom Removal"},
  {n:18, t:"It is an undeniable truth that besides the totality of symptoms nothing can by any means be discovered in diseases whereby the disease could express its need of relief.", topic:"Totality of Symptoms"},
  {n:19, t:"As diseases are nothing more than alterations in the state of health, which express themselves by symptoms, their cure also must consist only in the alteration of the state of health into the healthy condition.", topic:"Cure Defined"},
  {n:20, t:"It is only possible to know the curative properties of medicines by observing the changes in the health they produce in healthy people.", topic:"Drug Proving on Healthy"},
  {n:21, t:"We have no means of arriving at the knowledge of the internal physical changes except through the changes of health in healthy provers.", topic:"Proving — Basis of Knowledge"},
  {n:22, t:"There is no curative power in medicines except their ability to produce distinct alterations in the condition of health in human beings.", topic:"Curative Power of Medicines"},
  {n:24, t:"There is therefore no other possible way of employing medicines usefully in diseases than either the homoeopathic, allopathic, or enantiopathic method.", topic:"Methods of Treatment"},
  {n:25, t:"In homoeopathy the dose of the medicine acts upon the diseased part and the weaker affection (the natural disease) is extinguished by the stronger artificial disease.", topic:"Homoeopathic Principle"},
  {n:26, t:"A weaker dynamic affection is permanently extinguished in the living organism by a stronger one, if the latter is very similar to the former in its manifestations — the Natural Law of Cure.", topic:"Natural Law of Cure"},
  {n:27, t:"The curative power of medicines depends on their symptoms being similar to those of the disease but stronger, so that disease is most surely removed by a medicine capable of producing the most similar symptoms.", topic:"Similia Similibus Curentur"},
  {n:28, t:"The experience of all ages and lands has established homoeopathy as the only appropriate, the surest and most decisive mode of cure.", topic:"Homoeopathy — Supremacy"},
  {n:29, t:"As every disease consists only in a special morbid derangement of the vital force, the only mission of the physician is to remove this morbid derangement by giving the most similar medicine.", topic:"Goal of Treatment"},
  {n:30, t:"The human body appears to admit of being much more powerfully affected by medicines than by natural morbific agents — a circumstance which is of great importance for the cure.", topic:"Medicine > Natural Disease"},
  {n:43, t:"The medicine most suitable for the cure must exactly resemble the symptom-complex of the natural disease (the simillimum).", topic:"Simillimum"},
  {n:55, t:"Of the three modes of employing medicines in diseases, the homoeopathic alone is the one based on nature.", topic:"Homoeopathy — Natural Method"},
  {n:70, t:"Characteristic, particular, uncommon and peculiar signs and symptoms of the case must be kept most in view in the search for the homoeopathic remedy.", topic:"Characteristic Symptoms"},
  {n:72, t:"Human diseases are of two kinds: rapidly transient acute diseases, and chronic diseases.", topic:"Acute and Chronic Disease"},
  {n:73, t:"Acute diseases are rapid morbid processes of the vital force that tend to recovery or threaten life in a shorter or longer time.", topic:"Acute Disease Defined"},
  {n:74, t:"Chronic diseases originate from dynamic morbific agents that injure the vital force over many years.", topic:"Chronic Disease Defined"},
  {n:75, t:"The true natural chronic diseases are those that arise from a chronic miasm — Psora, Syphilis, and Sycosis.", topic:"Chronic Miasms"},
  {n:78, t:"Psora is the most ancient, most universal, most destructive and yet most misapprehended chronic miasmatic disease — the mother of all non-venereal chronic diseases.", topic:"Psora — King of Miasms"},
  {n:80, t:"This dreadful disease of psora covers many millions of forms of chronic disease under an incredible variety of faces.", topic:"Psora — Manifestations"},
  {n:81, t:"The secondary symptoms of psora can be as different as the family resemblances are unlike among men, yet all remain members of the same family.", topic:"Psoric Symptoms — Variety"},
  {n:96, t:"Among the patients' symptoms must be recorded the circumstances that can increase or lessen the complaints, and the times of day when they are worse or better.", topic:"Modalities in Case-Taking"},
  {n:98, t:"We must give heed to the mental and emotional temperament of the patient in all cases of disease. This is often the decisive factor in the choice of the remedy.", topic:"Mental Symptoms — Paramount"},
  {n:100, t:"The physician must carefully investigate the history and circumstances of the patient — past and present — and must inquire into the moral and mental nature of the patient.", topic:"Complete Case-Taking"},
  {n:102, t:"In collecting symptoms for chronic disease the physician must pay attention to the totality of symptoms that have been present at various times during the whole course of the disease.", topic:"Totality in Chronic Disease"},
  {n:105, t:"To be able to cure, the physician must possess knowledge of diseases, knowledge of medicines, and knowledge of their employment.", topic:"Physician's Three Needs"},
  {n:106, t:"The totality of symptoms of each individual disease is the sole indication, the only thing that can guide us in the selection of the remedy.", topic:"Totality Guides Prescription"},
  {n:110, t:"The only way to discover the medicinal powers of drugs is to test them on healthy human beings — drug proving.", topic:"Drug Proving — Only Way"},
  {n:117, t:"There are among proved medicines a few which call forth peculiar symptoms not found in any other medicine — which are characteristic and exclusively their own.", topic:"Characteristic Drug Symptoms"},
  {n:118, t:"Every medicine exhibits particular actions on the human organism which are not produced in the same manner by any other medicine.", topic:"Drug Individuality"},
  {n:119, t:"Just as all minerals, plants and animal substances differ so essentially from one another, so differ their pathogenetic effects on man.", topic:"Drug Uniqueness"},
  {n:128, t:"All medicines must be tested in the pure state — one at a time — unmixed with any other substance, and in health.", topic:"Pure Drug Proving"},
  {n:141, t:"The most perfect of all provings are those made on young, healthy, sensitive people of both sexes.", topic:"Ideal Provers"},
  {n:148, t:"The physician should avoid prescribing for a disease name — he must individualize and find the remedy that fits the patient.", topic:"Individualisation"},
  {n:149, t:"A disease is especially difficult to cure when the symptoms are scanty and one-sided — the remedy must match the few but characteristic symptoms.", topic:"One-Sided Disease"},
  {n:153, t:"The more striking, singular, uncommon and peculiar (characteristic) signs and symptoms of the case are chiefly and almost solely to be kept in view when selecting the homoeopathic remedy.", topic:"Characteristic Symptoms — §153"},
  {n:154, t:"The remedy whose symptom-picture contains the most similar symptoms to the disease of the patient will bring about the most rapid and permanent recovery.", topic:"Most Similar Remedy"},
  {n:155, t:"The symptoms to be cured are extinguished through the similar but stronger artificial disease produced by the medicine in the vital force.", topic:"Mechanism of Cure"},
  {n:156, t:"There are, however, cases where diseases produce quite peculiar sensations and symptoms which appear to have no corresponding drug pathogenesis.", topic:"Rare Symptoms"},
  {n:161, t:"In secondary action the vital force produces the opposite state — but only in those organs whose vital energy is not too strongly affected.", topic:"Primary and Secondary Action"},
  {n:169, t:"When two medicines are prescribed one after the other they must not be antidotes — they must be similar and complementary.", topic:"Complementary Medicines"},
  {n:171, t:"These skin diseases are most certainly and permanently cured by the internal homoeopathic remedy and never by local treatment which merely suppresses.", topic:"Internal Treatment — Skin"},
  {n:186, t:"Of all diseases the one-sided ones are the most difficult to cure.", topic:"One-Sided Diseases"},
  {n:195, t:"In chronic diseases, the remedy must be selected on the basis of the totality of symptoms.", topic:"Chronic Prescription"},
  {n:203, t:"Each antipsoric remedy must be allowed to act for a sufficiently long time before repeating or changing.", topic:"Long-Acting Antipsoric"},
  {n:206, t:"Before entering on anti-miasmatic treatment, the physician must first remove obstacles to recovery such as diet, habits, and domestic conditions.", topic:"Obstacles to Recovery"},
  {n:210, t:"Of all the morbid states, the mental and emotional symptoms are the most characteristic and individualising in chronic disease.", topic:"Mental Symptoms — Chronic"},
  {n:211, t:"This supreme importance of the emotional symptoms has a simple explanation: the mental and emotional state almost always determines the choice of the remedy.", topic:"Mental Symptoms Determine Remedy"},
  {n:212, t:"The physician should take particular note of the patient's moral and intellectual character — whether he is lively or stubborn, mild or violent.", topic:"Mental Character"},
  {n:213, t:"We shall therefore never be able to cure conformably to nature — i.e. homoeopathically — if we do not observe the mental symptoms.", topic:"Mental Symptoms — Essential"},
  {n:228, t:"As there is no homoeopathic antidote to administer, the physician must content himself with stopping the medicine and allowing the secondary action of the vital force to restore health.", topic:"Aggravation — Management"},
  {n:246, t:"Every perceptibly progressive and strikingly increasing amelioration during treatment completely precludes every repetition of the medicine as long as it lasts.", topic:"Repetition — When to Withhold"},
  {n:247, t:"Under the old treatment, medicines were given daily; in homoeopathy a single dose often suffices, acting sometimes for weeks.", topic:"Single Dose — Duration"},
  {n:248, t:"For the purpose of renewing the dose, it has been found most beneficial to give medicines in small doses at suitable intervals.", topic:"Dose Repetition — Guidelines"},
  {n:249, t:"Every case of disease must be treated by the physician who is thoroughly acquainted with all the circumstances of the patient's life.", topic:"Physician's Responsibility"},
  {n:252, t:"If during treatment of a chronic disease new and important symptoms appear, the remedy must be changed.", topic:"Changing Remedy"},
  {n:256, t:"After each treatment a new examination of the case must be made and the remedy adapted to the new totality.", topic:"Re-Examine and Re-Prescribe"},
  {n:260, t:"The most appropriate diet in chronic disease is the most natural, simple and wholesome food.", topic:"Diet in Chronic Disease"},
  {n:269, t:"The homoeopathic system develops the inner medicinal powers of crude substances by potentisation — a process that renders them immeasurably efficacious.", topic:"Potentisation — Purpose"},
  {n:270, t:"For homoeopathic potentisation: one part of substance mixed with 99 parts vehicle and succussed — this is the centesimal scale.", topic:"Centesimal Potency"},
  {n:271, t:"For outward appearance a dose of the 30th potency acts with great power in acute diseases and in cases requiring rapid action.", topic:"30th Potency — Acute"},
  {n:272, t:"Such a globule placed dry upon the tongue is one of the smallest doses for a moderate recent case of illness.", topic:"Dry Dose — Single Globule"},
  {n:273, t:"One single, simple medicine at a time should be given for curative purposes. To mix two medicines would make it impossible to judge their effects.", topic:"Single Medicine — Law"},
  {n:274, t:"Only one single simple medicinal substance should be administered to the patient at a time.", topic:"Simplex — One Medicine"},
  {n:275, t:"The dose of homoeopathically selected medicine can never be prepared small enough — the minutest dose suffices when the medicine is homoeopathically suited.", topic:"Minimum Dose"},
  {n:276, t:"For this reason alone the homoeopathic physician gives only one simple medicine at a time.", topic:"Simplex Reinforced"},
  {n:277, t:"For the same reasons, only the smallest possible dose should be given at one time. The medicinal disease must be stronger than the natural disease to extinguish it.", topic:"Minimum Dose Rationale"},
  {n:278, t:"The question is therefore: what is the most appropriate degree of smallness for rapid, gentle and permanent cure?", topic:"Minimum Dose — Question"},
  {n:279, t:"Pure experience must decide — and it has decided: that medicines in much smaller doses than are ordinarily used effect the cure.", topic:"Experience Decides Dose"},
  {n:280, t:"The dose must be just large enough to achieve the curative effect — not so large as to produce troublesome aggravations.", topic:"Optimal Dose"},
  {n:281, t:"The smallness of dose may go so far that the medicine will arouse only a very slight medicinal disease.", topic:"Infinitesimal Dose"},
  {n:285, t:"Every potentised medicine acts longest in the highest potencies, when prepared by many succussions.", topic:"High Potency — Duration"},
  {n:286, t:"The higher the degree of potency, the more rapidly the medicine acts on the vital force.", topic:"High Potency — Speed"},
  {n:287, t:"Olfaction of the potentised medicine may be used when the patient is extremely sensitive.", topic:"Olfaction as Dose"},
  {n:288, t:"The dose also depends on how long the patient has suffered — acute diseases require more frequent repetition than chronic ones.", topic:"Dose Frequency — Acute vs Chronic"},
  {n:291, t:"Water has the property of being readily impregnated with the medicinal powers of drugs. Water potencies may be given daily with advantage in chronic disease.", topic:"LM / Water Potency"},
];

// ─── REPERTORY RUBRICS ────────────────────────────────────────────────────────
const rubrics = [
  // MIND
  {r:"MIND; ANGER; easily", rem:[{n:"Nux Vomica",g:3},{n:"Chamomilla",g:3},{n:"Staphysagria",g:3},{n:"Bryonia",g:2},{n:"Hepar Sulph",g:2}]},
  {r:"MIND; ANXIETY; future, about", rem:[{n:"Calcarea Carb",g:3},{n:"Arsenicum Album",g:3},{n:"Lycopodium",g:2},{n:"Phosphorus",g:2},{n:"Psorinum",g:2}]},
  {r:"MIND; ANXIETY; health, about", rem:[{n:"Arsenicum Album",g:3},{n:"Calcarea Carb",g:3},{n:"Nitric Acid",g:2},{n:"Phosphorus",g:2}]},
  {r:"MIND; ANXIETY; conscience, of", rem:[{n:"Arsenicum Album",g:3},{n:"Aurum",g:3},{n:"Ignatia",g:2},{n:"Phosphorus",g:2}]},
  {r:"MIND; CONSOLATION; agg.", rem:[{n:"Natrum Mur",g:3},{n:"Sepia",g:3},{n:"Lilium Tig",g:2},{n:"Silica",g:1}]},
  {r:"MIND; FEAR; death, of", rem:[{n:"Arsenicum Album",g:3},{n:"Aconite",g:3},{n:"Platina",g:2},{n:"Calcarea",g:2}]},
  {r:"MIND; FEAR; alone, of being", rem:[{n:"Arsenicum Album",g:3},{n:"Phosphorus",g:3},{n:"Lycopodium",g:2},{n:"Kali Carb",g:2}]},
  {r:"MIND; FEAR; dark, of", rem:[{n:"Phosphorus",g:3},{n:"Stramonium",g:3},{n:"Calcarea",g:2},{n:"Arsenicum",g:2}]},
  {r:"MIND; GRIEF; ailments from", rem:[{n:"Ignatia",g:3},{n:"Natrum Mur",g:3},{n:"Staphysagria",g:2},{n:"Causticum",g:2}]},
  {r:"MIND; HURRY; always in a", rem:[{n:"Argentum Nit",g:3},{n:"Lilium Tig",g:3},{n:"Sulphur",g:2},{n:"Nux Vomica",g:2}]},
  {r:"MIND; INDIFFERENCE; loved ones, to", rem:[{n:"Sepia",g:3},{n:"Phosphoric Acid",g:3},{n:"Carbo Veg",g:2},{n:"Platina",g:2}]},
  {r:"MIND; JEALOUSY", rem:[{n:"Lachesis",g:3},{n:"Hyoscyamus",g:3},{n:"Nux Vomica",g:2},{n:"Apis",g:2}]},
  {r:"MIND; LOQUACITY", rem:[{n:"Lachesis",g:3},{n:"Hyoscyamus",g:3},{n:"Stramonium",g:3},{n:"Coffea",g:2}]},
  {r:"MIND; MEMORY; weakness", rem:[{n:"Baryta Carb",g:3},{n:"Calcarea",g:3},{n:"Natrum Mur",g:2},{n:"Phosphoric Acid",g:2}]},
  {r:"MIND; PRIDE; haughtiness", rem:[{n:"Platina",g:3},{n:"Lycopodium",g:2},{n:"Palladium",g:2},{n:"Staphysagria",g:1}]},
  {r:"MIND; RESTLESSNESS; night", rem:[{n:"Arsenicum Album",g:3},{n:"Rhus Tox",g:3},{n:"Aconite",g:2},{n:"Coffea",g:2}]},
  {r:"MIND; SADNESS; music; from", rem:[{n:"Natrum Carb",g:3},{n:"Graphites",g:3},{n:"Aurum",g:2},{n:"Natrum Sulph",g:2}]},
  {r:"MIND; SUICIDAL DISPOSITION", rem:[{n:"Aurum",g:3},{n:"Natrum Sulph",g:3},{n:"Nux Vomica",g:2},{n:"Arsenicum",g:2}]},
  {r:"MIND; SYMPATHY; compassion", rem:[{n:"Causticum",g:3},{n:"Phosphorus",g:3},{n:"Staphysagria",g:2},{n:"Arsenicum",g:2}]},
  {r:"MIND; TIMIDITY; bashful", rem:[{n:"Baryta Carb",g:3},{n:"Lycopodium",g:2},{n:"Pulsatilla",g:2},{n:"Silica",g:2}]},
  {r:"MIND; WEEPING; consolation; amel.", rem:[{n:"Pulsatilla",g:3},{n:"Phosphorus",g:2},{n:"Calc-p.",g:1}]},
  {r:"MIND; WEEPING; music; from", rem:[{n:"Graphites",g:3},{n:"Natrum Mur",g:2},{n:"Aurum",g:2}]},
  // GENERALS
  {r:"GENERALS; AGGRAVATION; 10 AM", rem:[{n:"Natrum Mur",g:3},{n:"Stannum",g:3},{n:"Gelsemium",g:2}]},
  {r:"GENERALS; AGGRAVATION; 11 AM", rem:[{n:"Sulphur",g:3},{n:"Natrum Mur",g:2},{n:"Arsenicum",g:1}]},
  {r:"GENERALS; AGGRAVATION; midnight; after", rem:[{n:"Arsenicum Album",g:3},{n:"Calcarea",g:2},{n:"Drosera",g:2}]},
  {r:"GENERALS; AGGRAVATION; 2-4 AM", rem:[{n:"Arsenicum Album",g:3},{n:"Kali Carb",g:3},{n:"Thuja",g:2}]},
  {r:"GENERALS; AGGRAVATION; 4–8 PM", rem:[{n:"Lycopodium",g:3},{n:"Helleborus",g:2},{n:"Colchicum",g:2}]},
  {r:"GENERALS; COLD; agg.", rem:[{n:"Arsenicum Album",g:3},{n:"Calcarea",g:3},{n:"Kali Carb",g:3},{n:"Silica",g:3}]},
  {r:"GENERALS; COLD; wet weather; agg.", rem:[{n:"Rhus Tox",g:3},{n:"Calcarea",g:3},{n:"Dulcamara",g:3},{n:"Natrum Sulph",g:2}]},
  {r:"GENERALS; FOOD; eggs; desire", rem:[{n:"Calcarea",g:3},{n:"Calcarea Phos",g:2}]},
  {r:"GENERALS; FOOD; fat; agg.", rem:[{n:"Pulsatilla",g:3},{n:"Carbo Veg",g:2},{n:"Cyclamen",g:2}]},
  {r:"GENERALS; FOOD; salt; desire", rem:[{n:"Natrum Mur",g:3},{n:"Calcarea",g:2},{n:"Phosphorus",g:2},{n:"Veratrum",g:2}]},
  {r:"GENERALS; FOOD; sweets; desire", rem:[{n:"Lycopodium",g:3},{n:"Argentum Nit",g:3},{n:"Sulphur",g:2},{n:"China",g:2}]},
  {r:"GENERALS; HEAT; lack of vital heat", rem:[{n:"Calcarea",g:3},{n:"Silica",g:3},{n:"Baryta Carb",g:2},{n:"Arsenicum",g:2}]},
  {r:"GENERALS; LOSS OF FLUIDS; agg.", rem:[{n:"China",g:3},{n:"Carbo Veg",g:3},{n:"Arsenicum",g:2},{n:"Phosphoric Acid",g:2}]},
  {r:"GENERALS; MOTION; agg.", rem:[{n:"Bryonia",g:3},{n:"Colocynthis",g:2},{n:"Nux Vomica",g:2}]},
  {r:"GENERALS; MOTION; amel.", rem:[{n:"Rhus Tox",g:3},{n:"Pulsatilla",g:2},{n:"Ferrum",g:2},{n:"Dulcamara",g:1}]},
  {r:"GENERALS; PERIODICITY", rem:[{n:"China",g:3},{n:"Arsenicum",g:3},{n:"Natrum Mur",g:3},{n:"Sulphur",g:2}]},
  {r:"GENERALS; SIDE; left", rem:[{n:"Lachesis",g:3},{n:"Spigelia",g:3},{n:"Natrum Mur",g:2}]},
  {r:"GENERALS; SIDE; right", rem:[{n:"Lycopodium",g:3},{n:"Belladonna",g:2},{n:"Chelidonium",g:3},{n:"Apis",g:2}]},
  {r:"GENERALS; SUPPRESSION; complaints from", rem:[{n:"Sulphur",g:3},{n:"Psorinum",g:3},{n:"Thuja",g:2},{n:"Silica",g:2}]},
  {r:"GENERALS; WARM ROOM; agg.", rem:[{n:"Pulsatilla",g:3},{n:"Apis",g:3},{n:"Lycopodium",g:2},{n:"Sulphur",g:2}]},
  // HEAD
  {r:"HEAD; PAIN; forehead; morning", rem:[{n:"Bryonia",g:3},{n:"Nux Vomica",g:2},{n:"Belladonna",g:2}]},
  {r:"HEAD; PAIN; right side", rem:[{n:"Belladonna",g:3},{n:"Sanguinaria",g:3},{n:"Iris Vers.",g:2}]},
  {r:"HEAD; PAIN; vertex; burning", rem:[{n:"Sulphur",g:3},{n:"Belladonna",g:2},{n:"Glonoine",g:2}]},
  {r:"HEAD; PERSPIRATION; occiput", rem:[{n:"Calcarea",g:3},{n:"Silica",g:3},{n:"Psorinum",g:2}]},
  // EYES
  {r:"EYE; LACHRYMATION; acrid", rem:[{n:"Euphrasia",g:3},{n:"Allium Cepa",g:1},{n:"Arsenicum",g:2}]},
  {r:"EYE; INFLAMMATION; conjunctivae", rem:[{n:"Apis",g:3},{n:"Argentum Nit",g:3},{n:"Euphrasia",g:3}]},
  // NOSE
  {r:"NOSE; CORYZA; bland, watery", rem:[{n:"Allium Cepa",g:3},{n:"Euphrasia",g:1},{n:"Pulsatilla",g:2}]},
  {r:"NOSE; SNEEZING; paroxysmal", rem:[{n:"Sabadilla",g:3},{n:"Arsenicum",g:2},{n:"Allium Cepa",g:2}]},
  // THROAT
  {r:"THROAT; PAIN; swallowing; agg.", rem:[{n:"Belladonna",g:3},{n:"Hepar Sulph",g:3},{n:"Mercurius",g:3},{n:"Lachesis",g:2}]},
  {r:"THROAT; SWALLOWING; inability to swallow solids but liquids pass", rem:[{n:"Baryta Carb",g:3},{n:"Alumina",g:2}]},
  // STOMACH
  {r:"STOMACH; NAUSEA; persistent", rem:[{n:"Ipecac",g:3},{n:"Nux Vomica",g:2},{n:"Colchicum",g:2}]},
  {r:"STOMACH; PAIN; eating; after", rem:[{n:"Nux Vomica",g:3},{n:"Pulsatilla",g:2},{n:"Lycopodium",g:2},{n:"Carbo Veg",g:2}]},
  {r:"STOMACH; THIRST; unquenchable", rem:[{n:"Arsenicum",g:3},{n:"Bryonia",g:3},{n:"Phosphorus",g:2}]},
  {r:"STOMACH; THIRST; absence of", rem:[{n:"Pulsatilla",g:3},{n:"Apis",g:3},{n:"Gelsemium",g:2}]},
  // ABDOMEN
  {r:"ABDOMEN; DISTENSION; flatulent", rem:[{n:"Carbo Veg",g:3},{n:"Lycopodium",g:3},{n:"China",g:3},{n:"Sulphur",g:2}]},
  {r:"ABDOMEN; PAIN; colic; bending double; amel.", rem:[{n:"Colocynthis",g:3},{n:"Magnesia Phos",g:3},{n:"Belladonna",g:1}]},
  // STOOL
  {r:"STOOL; CONSTIPATION; no desire", rem:[{n:"Alumina",g:3},{n:"Baryta Mur",g:2},{n:"Bryonia",g:2},{n:"Opium",g:3}]},
  {r:"STOOL; DIARRHOEA; morning; driving out of bed", rem:[{n:"Sulphur",g:3},{n:"Aloe",g:3},{n:"Phosphorus",g:2}]},
  // URINARY
  {r:"BLADDER; URGING; frequent, constant", rem:[{n:"Cantharis",g:3},{n:"Staphysagria",g:3},{n:"Mercurius",g:2}]},
  {r:"URINE; INVOLUNTARY; coughing, during", rem:[{n:"Causticum",g:3},{n:"Pulsatilla",g:2},{n:"Natrum Mur",g:2}]},
  // CHEST
  {r:"CHEST; PALPITATION; anxiety; with", rem:[{n:"Arsenicum",g:3},{n:"Aconite",g:3},{n:"Coffea",g:2},{n:"Phosphorus",g:2}]},
  {r:"CHEST; PAIN; stitching; inspiration; on", rem:[{n:"Bryonia",g:3},{n:"Kali Carb",g:3},{n:"Sulphur",g:2}]},
  // BACK
  {r:"BACK; PAIN; lumbar; menses; during", rem:[{n:"Sepia",g:3},{n:"Kali Carb",g:3},{n:"Pulsatilla",g:2}]},
  {r:"BACK; PAIN; cervical; motion; agg.", rem:[{n:"Bryonia",g:3},{n:"Rhus Tox",g:2},{n:"Calcarea",g:2}]},
  // EXTREMITIES
  {r:"EXTREMITIES; RESTLESSNESS; lower limbs", rem:[{n:"Zincum",g:3},{n:"Rhus Tox",g:3},{n:"Medorrhinum",g:2}]},
  {r:"EXTREMITIES; CRAMPS; calves", rem:[{n:"Cuprum",g:3},{n:"Magnesia Phos",g:3},{n:"Calcarea",g:2},{n:"Veratrum",g:2}]},
  {r:"EXTREMITIES; PERSPIRATION; feet; offensive", rem:[{n:"Silica",g:3},{n:"Baryta Carb",g:2},{n:"Calcarea",g:2}]},
  // SLEEP
  {r:"SLEEP; SLEEPLESSNESS; joy; from", rem:[{n:"Coffea",g:3},{n:"Aconite",g:2},{n:"Ignatia",g:1}]},
  {r:"SLEEP; SLEEPLESSNESS; thoughts; from", rem:[{n:"Coffea",g:3},{n:"Nux Vomica",g:2},{n:"Belladonna",g:2},{n:"Arsenicum",g:2}]},
  {r:"SLEEP; WAKING; 3 AM", rem:[{n:"Sulphur",g:3},{n:"Arsenicum",g:3},{n:"Kali Carb",g:3}]},
  // SKIN
  {r:"SKIN; ITCHING; warmth; agg.", rem:[{n:"Sulphur",g:3},{n:"Psorinum",g:3},{n:"Mezereum",g:2}]},
  {r:"SKIN; WARTS; large, seedy", rem:[{n:"Thuja",g:3},{n:"Nitric Acid",g:3},{n:"Causticum",g:2}]},
  {r:"SKIN; ERUPTIONS; herpetic", rem:[{n:"Natrum Mur",g:3},{n:"Sepia",g:3},{n:"Graphites",g:2},{n:"Rhus Tox",g:2}]},
  // FEVER
  {r:"FEVER; CHILLS; spine; up and down", rem:[{n:"Gelsemium",g:3},{n:"China",g:2},{n:"Natrum Mur",g:2}]},
  {r:"FEVER; PERSPIRATION; offensive", rem:[{n:"Mercurius",g:3},{n:"Sulphur",g:3},{n:"Arsenicum",g:2}]},
  // FEMALE
  {r:"FEMALE; MENSES; late; too", rem:[{n:"Pulsatilla",g:3},{n:"Calcarea",g:3},{n:"Graphites",g:2},{n:"Sepia",g:2}]},
  {r:"FEMALE; MENSES; early; too", rem:[{n:"Nux Vomica",g:3},{n:"Calcarea",g:2},{n:"Phosphorus",g:2}]},
  {r:"FEMALE; PAIN; ovaries; left", rem:[{n:"Lachesis",g:3},{n:"Thuja",g:2},{n:"Lilium Tig",g:2}]},
  // RESPIRATORY
  {r:"COUGH; CROUPY; midnight; before", rem:[{n:"Spongia",g:3},{n:"Aconite",g:3},{n:"Hepar Sulph",g:2}]},
  {r:"COUGH; SPASMODIC; whooping", rem:[{n:"Drosera",g:3},{n:"Cuprum",g:3},{n:"Ipecac",g:2},{n:"Belladonna",g:2}]},
  {r:"COUGH; WORSE; lying down", rem:[{n:"Hyoscyamus",g:3},{n:"Drosera",g:3},{n:"Conium",g:2}]},
];

// ─── BUILD DOCUMENTS ─────────────────────────────────────────────────────────
async function run() {
  console.log("\n🌿 NeoHomeo AI — Full Knowledge Base Ingestion\n");

  // Remedies
  console.log(`📚 Ingesting ${remedies.length} remedies...`);
  await upsert(remedies.map(r => ({
    source: "materia_medica",
    category: r.name,
    title: `Materia Medica: ${r.name} (${r.abbr})`,
    content: [
      `REMEDY: ${r.name} (${r.abbr}) — ${r.cat.toUpperCase()}`,
      `CONSTITUTION: ${r.const}`,
      `KEYNOTES:\n${r.keys.map(k=>`• ${k}`).join("\n")}`,
      `MIND:\n${r.mind.map(m=>`• ${m}`).join("\n")}`,
      `MODALITIES:\nWorse: ${r.worse.join(", ")}\nBetter: ${r.better.join(", ")}`,
      `RELATIONSHIPS:\nComplementary: ${r.comp.join(", ")}\nAntidotes: ${r.anti.join(", ")}`,
    ].join("\n\n"),
    metadata: { remedy: r.name, abbreviation: r.abbr, category: r.cat },
  })));

  // Organon
  console.log(`\n📖 Ingesting ${organon.length} Organon aphorisms...`);
  await upsert(organon.map(a => ({
    source: "organon",
    category: `Aphorism §${a.n}`,
    title: `Organon §${a.n}: ${a.topic}`,
    content: `APHORISM §${a.n} — ${a.topic.toUpperCase()}\n\n"${a.t}"\n\n— Samuel Hahnemann, Organon of Medicine (6th Edition)`,
    metadata: { aphorism_number: a.n, topic: a.topic },
  })));

  // Rubrics
  console.log(`\n🗂  Ingesting ${rubrics.length} repertory rubrics...`);
  await upsert(rubrics.map(r => ({
    source: "repertory",
    category: r.r.split(";")[0].trim(),
    title: `Repertory: ${r.r}`,
    content: [
      `RUBRIC: ${r.r}`,
      `Grade 3: ${r.rem.filter(x=>x.g===3).map(x=>x.n).join(", ")||"—"}`,
      `Grade 2: ${r.rem.filter(x=>x.g===2).map(x=>x.n).join(", ")||"—"}`,
      `Grade 1: ${r.rem.filter(x=>x.g===1).map(x=>x.n).join(", ")||"—"}`,
      `FULL LIST: ${r.rem.map(x=>`${x.n}[${x.g}]`).join(", ")}`,
    ].join("\n"),
    metadata: { rubric: r.r, top_remedy: r.rem[0]?.n },
  })));

  console.log("\n✅ Done!\n");
}

run().catch(console.error);
